### ISSUE TITLE
0929漢化檔無法繁體中文化

### ISSUE THREAD

**Issue by mosesmoon** [Megumi-B/GTA4_FullTran_CHT#1]
安裝方式跟0614不太一樣，似乎沒有包含fonts.wtd字型檔案了
0929漢化下載點:
https://mega.nz/folder/kHAEibjJ#b43B3LicVrEegGxK0YDk_Q

看大大能否更新一下繁體中文化的部分，感謝~

**Comment by mosesmoon** [comment]
自問自答一下，新版漢化把字型檔案改了位置，放在
plugins\GTA4.CHS\IV.png
plugins\GTA4.CHS\TBoGT.png
plugins\GTA4.CHS\TLAD.png
不再採用原本fonts.wtd
看大大能否提供原本pc TBoGT TLAD三個png檔案，我覆蓋看看。

**Comment by Megumi-B** [comment]
您好，目前使用漢化組最新版230704版，相信採用獨立檔案方式，只需修改font_chs.wtd即可。
如您有自行修改的需要，可以於https://github.com/Megumi-B/GTA4_FullTran_CHT/blob/main/230704_CHT/font_chs.png 下載。
目前三個故事都是採用同一png檔。
